-- Adds exercise additions from exercise_additions_cleaned_normalized.csv, skipping neck rows.
-- Uses existing exercises and exercise_muscles format only.

with seed_exercises (name, slug, category, equipment, movement_pattern, difficulty, instructions, notes) as (
  values
    ('Dumbbell Squat', 'dumbbell-squat', 'quads', array['dumbbell'], 'knee dominant', 'beginner', null, 'Added from user body-part table: Quadriceps; normalized name from Dumbbell Body Weight Squat'),
    ('Barbell Calf Raise', 'barbell-calf-raise', 'calves', array['barbell'], 'calf raise', 'intermediate', null, 'Added from user body-part table: Calves'),
    ('Dumbbell Close-Grip Bench Press', 'dumbbell-close-grip-bench-press', 'triceps', array['dumbbell'], 'elbow extension', 'beginner', null, 'Added from user body-part table: Triceps'),
    ('Barbell Wide-Grip Biceps Curl', 'barbell-wide-grip-biceps-curl', 'biceps', array['barbell'], 'elbow flexion', 'intermediate', null, 'Added from user body-part table: Biceps'),
    ('Machine Ab Crunch', 'machine-ab-crunch', 'core', array['machine'], 'trunk flexion', 'beginner', null, 'Added from user body-part table: Abs'),
    ('Barbell Deficit Deadlift', 'barbell-deficit-deadlift', 'hamstrings', array['barbell'], 'hip hinge', 'advanced', null, 'Added from user body-part table: Glutes_Hamstrings; normalized name from Barbell Deadlifts from Deficit'),
    ('Barbell Incline Bench Row', 'barbell-incline-bench-row', 'back', array['barbell'], 'horizontal pull', 'intermediate', null, 'Added from user body-part table: Back'),
    ('Barbell Close-Grip Biceps Curl', 'barbell-close-grip-biceps-curl', 'biceps', array['barbell'], 'elbow flexion', 'intermediate', null, 'Added from user body-part table: Biceps'),
    ('Dumbbell Ab Twist', 'dumbbell-ab-twist', 'core', array['dumbbell'], 'trunk flexion', 'beginner', null, 'Added from user body-part table: Abs'),
    ('Barbell Wrist Curl', 'barbell-wrist-curl', 'forearms', array['barbell'], 'wrist flexion', 'intermediate', null, 'Added from user body-part table: Other'),
    ('Barbell Block Deadlift', 'barbell-block-deadlift', 'hamstrings', array['barbell'], 'hip hinge', 'advanced', null, 'Added from user body-part table: Glutes_Hamstrings; normalized name from Barbell Deadlifts from Blocks'),
    ('Barbell Preacher Biceps Curl', 'barbell-preacher-biceps-curl', 'biceps', array['barbell'], 'elbow flexion', 'intermediate', null, 'Added from user body-part table: Biceps'),
    ('Barbell Plate Ab Twist', 'barbell-plate-ab-twist', 'core', array['barbell', 'weight plate'], 'trunk flexion', 'intermediate', null, 'Added from user body-part table: Abs'),
    ('Barbell Jump Squat', 'barbell-jump-squat', 'quads', array['barbell'], 'knee dominant', 'advanced', null, 'Added from user body-part table: Quadriceps'),
    ('Cable Flat Bench Triceps Extension', 'cable-flat-bench-triceps-extension', 'triceps', array['cable'], 'elbow extension', 'beginner', null, 'Added from user body-part table: Triceps'),
    ('Dumbbell Preacher Biceps Curl', 'dumbbell-preacher-biceps-curl', 'biceps', array['dumbbell'], 'elbow flexion', 'beginner', null, 'Added from user body-part table: Biceps'),
    ('Barbell Reverse-Grip Bent-Over Row', 'barbell-reverse-grip-bent-over-row', 'back', array['barbell'], 'horizontal pull', 'intermediate', null, 'Added from user body-part table: Back; normalized name from Barbell Reverse Grip Bent Over'),
    ('Barbell Incline Bench Triceps Extension', 'barbell-incline-bench-triceps-extension', 'triceps', array['barbell'], 'elbow extension', 'intermediate', null, 'Added from user body-part table: Triceps'),
    ('Weighted Hanging Leg Raise', 'weighted-hanging-leg-raise', 'core', array['bodyweight', 'weight plate'], 'trunk flexion', 'advanced', null, 'Added from user body-part table: Abs'),
    ('Dumbbell Reverse-Grip Bent-Over Row', 'dumbbell-reverse-grip-bent-over-row', 'back', array['dumbbell'], 'horizontal pull', 'beginner', null, 'Added from user body-part table: Back; normalized name from Dumbbell Reverse Grip Bent Over'),
    ('Dumbbell Incline Bench Triceps Extension', 'dumbbell-incline-bench-triceps-extension', 'triceps', array['dumbbell'], 'elbow extension', 'beginner', null, 'Added from user body-part table: Triceps'),
    ('Cable Incline Bench Biceps Curl', 'cable-incline-bench-biceps-curl', 'biceps', array['cable'], 'elbow flexion', 'beginner', null, 'Added from user body-part table: Biceps'),
    ('Barbell Bulgarian Split Squat', 'barbell-bulgarian-split-squat', 'quads', array['barbell'], 'knee dominant', 'advanced', null, 'Added from user body-part table: Quadriceps; normalized name from Barbell Bulgarian Split-Squat'),
    ('Dumbbell Stiff-Legged Deadlift', 'dumbbell-stiff-legged-deadlift', 'hamstrings', array['dumbbell'], 'hip hinge', 'intermediate', null, 'Added from user body-part table: Glutes_Hamstrings'),
    ('Cable Incline Bench Triceps Extension', 'cable-incline-bench-triceps-extension', 'triceps', array['cable'], 'elbow extension', 'beginner', null, 'Added from user body-part table: Triceps'),
    ('Weighted Plank', 'weighted-plank', 'core', array['bodyweight', 'weight plate'], 'anti-extension/anti-rotation', 'advanced', null, 'Added from user body-part table: Abs'),
    ('Machine Decline Chest Press', 'machine-decline-chest-press', 'chest', array['machine'], 'horizontal push', 'beginner', null, 'Added from user body-part table: Chest'),
    ('Barbell Decline Bench Triceps Extension', 'barbell-decline-bench-triceps-extension', 'triceps', array['barbell'], 'elbow extension', 'intermediate', null, 'Added from user body-part table: Triceps'),
    ('Dumbbell Reverse-Grip Biceps Curl', 'dumbbell-reverse-grip-biceps-curl', 'biceps', array['dumbbell'], 'elbow flexion', 'beginner', null, 'Added from user body-part table: Biceps'),
    ('Bodyweight Bulgarian Split Squat', 'bodyweight-bulgarian-split-squat', 'quads', array['bodyweight'], 'knee dominant', 'advanced', null, 'Added from user body-part table: Quadriceps; normalized name from Body Weight Bulgarian Split-Squat'),
    ('Dumbbell Hip Thrust', 'dumbbell-hip-thrust', 'glutes', array['dumbbell'], 'hip thrust', 'beginner', null, 'Added from user body-part table: Glutes_Hamstrings'),
    ('Barbell One-Arm Row', 'barbell-one-arm-row', 'back', array['barbell'], 'horizontal pull', 'advanced', null, 'Added from user body-part table: Back'),
    ('Dumbbell Decline Bench Triceps Extension', 'dumbbell-decline-bench-triceps-extension', 'triceps', array['dumbbell'], 'elbow extension', 'beginner', null, 'Added from user body-part table: Triceps'),
    ('Smith Machine Bent Over Row', 'smith-machine-bent-over-row', 'back', array['smith machine'], 'horizontal pull', 'beginner', null, 'Added from user body-part table: Back'),
    ('Cable Standing Shoulder Press', 'cable-standing-shoulder-press', 'shoulders', array['cable'], 'vertical push', 'beginner', null, 'Added from user body-part table: Shoulders; normalized name from Cable Standing Shoulder Press (Standing)'),
    ('Cable Decline Bench Triceps Extension', 'cable-decline-bench-triceps-extension', 'triceps', array['cable'], 'elbow extension', 'beginner', null, 'Added from user body-part table: Triceps'),
    ('Barbell Concentration Biceps Curl', 'barbell-concentration-biceps-curl', 'biceps', array['barbell'], 'elbow flexion', 'intermediate', null, 'Added from user body-part table: Biceps'),
    ('Dumbbell Glute Bridge', 'dumbbell-glute-bridge', 'glutes', array['dumbbell'], 'hip thrust', 'beginner', null, 'Added from user body-part table: Glutes_Hamstrings'),
    ('Smith Machine Decline Chest Press', 'smith-machine-decline-chest-press', 'chest', array['smith machine'], 'horizontal push', 'beginner', null, 'Added from user body-part table: Chest'),
    ('Barbell Chest-Supported T-Bar Row', 'barbell-chest-supported-t-bar-row', 'back', array['barbell'], 'horizontal pull', 'intermediate', null, 'Added from user body-part table: Back'),
    ('Seated Cable Shoulder Press', 'seated-cable-shoulder-press', 'shoulders', array['cable'], 'vertical push', 'beginner', null, 'Added from user body-part table: Shoulders; normalized name from Cable Shoulder Press (Seated)'),
    ('Barbell Overhead Triceps Extension', 'barbell-overhead-triceps-extension', 'triceps', array['barbell'], 'elbow extension', 'intermediate', null, 'Added from user body-part table: Triceps'),
    ('Bodyweight Walking Lunge', 'bodyweight-walking-lunge', 'quads', array['bodyweight'], 'knee dominant', 'beginner', null, 'Added from user body-part table: Quadriceps; normalized name from Body Weight Walking Lunge'),
    ('Zercher Carries', 'zercher-carries', 'core', array['barbell'], 'trunk flexion', 'advanced', null, 'Added from user body-part table: Abs'),
    ('Barbell Standing Lunge', 'barbell-standing-lunge', 'quads', array['barbell'], 'knee dominant', 'intermediate', null, 'Added from user body-part table: Quadriceps'),
    ('Cable Incline Bench Press', 'cable-incline-bench-press', 'chest', array['cable'], 'horizontal push', 'beginner', null, 'Added from user body-part table: Chest'),
    ('Barbell Front Raise', 'barbell-front-raise', 'shoulders', array['barbell'], 'shoulder raise', 'intermediate', null, 'Added from user body-part table: Shoulders'),
    ('Cable One-Arm Overhead Triceps Extension', 'cable-one-arm-overhead-triceps-extension', 'triceps', array['cable'], 'elbow extension', 'advanced', null, 'Added from user body-part table: Triceps'),
    ('Machine Biceps Curl', 'machine-biceps-curl', 'biceps', array['machine'], 'elbow flexion', 'beginner', null, 'Added from user body-part table: Biceps'),
    ('Barbell Step-Up', 'barbell-step-up', 'quads', array['barbell'], 'knee dominant', 'intermediate', null, 'Added from user body-part table: Quadriceps; normalized name from Barbell Step Up'),
    ('Weighted Push-Up', 'weighted-push-up', 'chest', array['bodyweight', 'weight plate'], 'horizontal push', 'advanced', null, 'Added from user body-part table: Chest'),
    ('Machine Iso Row', 'machine-iso-row', 'back', array['machine'], 'horizontal pull', 'beginner', null, 'Added from user body-part table: Back'),
    ('Cable Overhead Curl', 'cable-overhead-curl', 'biceps', array['cable'], 'elbow flexion', 'beginner', null, 'Added from user body-part table: Biceps'),
    ('Bodyweight Glute-Ham Raise', 'bodyweight-glute-ham-raise', 'hamstrings', array['bodyweight'], 'hip hinge', 'beginner', null, 'Added from user body-part table: Glutes_Hamstrings; normalized name from Body Weight Glute-Ham Raise'),
    ('Weighted Pull-Up', 'weighted-pull-up', 'back', array['bodyweight', 'weight plate', 'pull-up bar'], 'vertical pull', 'advanced', null, 'Added from user body-part table: Back'),
    ('Dumbbell One-Arm Lateral Raise', 'dumbbell-one-arm-lateral-raise', 'shoulders', array['dumbbell'], 'shoulder raise', 'advanced', null, 'Added from user body-part table: Shoulders'),
    ('Weighted Incline Push-Up', 'weighted-incline-push-up', 'chest', array['bodyweight', 'weight plate'], 'horizontal push', 'advanced', null, 'Added from user body-part table: Chest'),
    ('Dumbbell Bent-Over Triceps Extension', 'dumbbell-bent-over-triceps-extension', 'triceps', array['dumbbell'], 'elbow extension', 'beginner', null, 'Added from user body-part table: Triceps; normalized name from Dumbbell Bent Over Triceps Extension'),
    ('Dumbbell One-Arm Biceps Curl', 'dumbbell-one-arm-biceps-curl', 'biceps', array['dumbbell'], 'elbow flexion', 'advanced', null, 'Added from user body-part table: Biceps'),
    ('Smith Machine Close-Grip Bench Press', 'smith-machine-close-grip-bench-press', 'triceps', array['smith machine'], 'elbow extension', 'beginner', null, 'Added from user body-part table: Triceps'),
    ('Cable One-Arm Biceps Curl', 'cable-one-arm-biceps-curl', 'biceps', array['cable'], 'elbow flexion', 'advanced', null, 'Added from user body-part table: Biceps'),
    ('Machine Hip Thrust', 'machine-hip-thrust', 'glutes', array['machine'], 'hip thrust', 'beginner', null, 'Added from user body-part table: Glutes_Hamstrings; normalized name from Hip Thrust Machine'),
    ('Weighted Decline Push-Up', 'weighted-decline-push-up', 'chest', array['bodyweight', 'weight plate'], 'horizontal push', 'advanced', null, 'Added from user body-part table: Chest'),
    ('Weighted Triceps Dip', 'weighted-triceps-dip', 'triceps', array['bodyweight', 'weight plate', 'dip bars'], 'elbow extension', 'advanced', null, 'Added from user body-part table: Triceps; normalized name from Weighted Dips (Triceps Variation)'),
    ('Weighted Chin-Up', 'weighted-chin-up', 'biceps', array['bodyweight', 'weight plate', 'pull-up bar'], 'elbow flexion', 'advanced', null, 'Added from user body-part table: Biceps'),
    ('Cable Reverse-Grip Lat Pulldown', 'cable-reverse-grip-lat-pulldown', 'back', array['cable'], 'vertical pull', 'beginner', null, 'Added from user body-part table: Back; normalized name from Cable Reverse-Grip Lat Pull-Down'),
    ('Machine Assisted Chin-Up', 'machine-assisted-chin-up', 'biceps', array['machine'], 'elbow flexion', 'beginner', null, 'Added from user body-part table: Biceps'),
    ('Cable V-Bar Lat Pulldown', 'cable-v-bar-lat-pulldown', 'back', array['cable'], 'vertical pull', 'beginner', null, 'Added from user body-part table: Back; normalized name from Cable V-Bar Lat Pull-Down'),
    ('Cable One-Arm Lat Pulldown', 'cable-one-arm-lat-pulldown', 'back', array['cable'], 'vertical pull', 'advanced', null, 'Added from user body-part table: Back; normalized name from Cable One-Arm Lat Pull-Down'),
    ('Cable V-Bar Triceps Pushdown', 'cable-v-bar-triceps-pushdown', 'triceps', array['cable'], 'elbow extension', 'beginner', null, 'Added from user body-part table: Triceps; normalized name from Cable V-Bar Triceps Push-Down'),
    ('Dumbbell Decline Bench Fly', 'dumbbell-decline-bench-fly', 'chest', array['dumbbell'], 'fly', 'beginner', null, 'Added from user body-part table: Chest'),
    ('Machine Back Extension', 'machine-back-extension', 'back', array['machine'], 'spinal extension', 'beginner', null, 'Added from user body-part table: Back'),
    ('Cable Reverse-Grip Triceps Pushdown', 'cable-reverse-grip-triceps-pushdown', 'triceps', array['cable'], 'elbow extension', 'beginner', null, 'Added from user body-part table: Triceps; normalized name from Cable Reverse-Grip Triceps Push-Down'),
    ('Machine Upright Row', 'machine-upright-row', 'shoulders', array['machine'], 'upright row', 'beginner', null, 'Added from user body-part table: Shoulders'),
    ('Weighted Bench Dip', 'weighted-bench-dip', 'triceps', array['bodyweight', 'weight plate', 'bench'], 'elbow extension', 'advanced', null, 'Added from user body-part table: Triceps'),
    ('Cable Upright Row', 'cable-upright-row', 'shoulders', array['cable'], 'upright row', 'beginner', null, 'Added from user body-part table: Shoulders'),
    ('Machine Shrug', 'machine-shrug', 'back', array['machine'], 'shrug', 'beginner', null, 'Added from user body-part table: Back'),
    ('Cable Incline Bench Fly', 'cable-incline-bench-fly', 'chest', array['cable'], 'fly', 'beginner', null, 'Added from user body-part table: Chest'),
    ('Smith Machine Chest-Supported Row', 'smith-machine-chest-supported-row', 'back', array['smith machine'], 'horizontal pull', 'beginner', null, 'Added from user body-part table: Back'),
    ('Cable Flat Bench Fly', 'cable-flat-bench-fly', 'chest', array['cable'], 'fly', 'beginner', null, 'Added from user body-part table: Chest'),
    ('Machine Chest-Supported Low Row', 'machine-chest-supported-low-row', 'back', array['machine'], 'horizontal pull', 'beginner', null, 'Added from user body-part table: Back; normalized name from Machine Chest Supported Low Row')
)
insert into public.exercises (name, slug, category, equipment, movement_pattern, difficulty, instructions, notes, is_builtin)
select se.name, se.slug, se.category::public.exercise_category, se.equipment, se.movement_pattern, se.difficulty::public.difficulty_level, se.instructions, se.notes, true
from seed_exercises se
where not exists (
  select 1 from public.exercises e where e.slug = se.slug and e.is_builtin = true
);

with seed_exercise_muscles (exercise_slug, muscle_slug, role) as (
  values
    ('dumbbell-squat', 'quadriceps', 'primary'::public.muscle_role),
    ('dumbbell-squat', 'gluteus-maximus', 'secondary'::public.muscle_role),
    ('dumbbell-squat', 'hamstrings', 'secondary'::public.muscle_role),
    ('barbell-calf-raise', 'calves', 'primary'::public.muscle_role),
    ('dumbbell-close-grip-bench-press', 'triceps-brachii', 'primary'::public.muscle_role),
    ('dumbbell-close-grip-bench-press', 'pectoralis-major', 'secondary'::public.muscle_role),
    ('dumbbell-close-grip-bench-press', 'shoulders', 'secondary'::public.muscle_role),
    ('barbell-wide-grip-biceps-curl', 'biceps-brachii', 'primary'::public.muscle_role),
    ('barbell-wide-grip-biceps-curl', 'forearms', 'secondary'::public.muscle_role),
    ('machine-ab-crunch', 'core', 'primary'::public.muscle_role),
    ('barbell-deficit-deadlift', 'hamstrings', 'primary'::public.muscle_role),
    ('barbell-deficit-deadlift', 'gluteus-maximus', 'secondary'::public.muscle_role),
    ('barbell-deficit-deadlift', 'spinal-erectors', 'secondary'::public.muscle_role),
    ('barbell-incline-bench-row', 'back', 'primary'::public.muscle_role),
    ('barbell-incline-bench-row', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('barbell-incline-bench-row', 'posterior-deltoid', 'secondary'::public.muscle_role),
    ('barbell-close-grip-biceps-curl', 'biceps-brachii', 'primary'::public.muscle_role),
    ('barbell-close-grip-biceps-curl', 'forearms', 'secondary'::public.muscle_role),
    ('dumbbell-ab-twist', 'core', 'primary'::public.muscle_role),
    ('dumbbell-ab-twist', 'obliques', 'secondary'::public.muscle_role),
    ('barbell-wrist-curl', 'forearms', 'primary'::public.muscle_role),
    ('barbell-block-deadlift', 'hamstrings', 'primary'::public.muscle_role),
    ('barbell-block-deadlift', 'gluteus-maximus', 'secondary'::public.muscle_role),
    ('barbell-block-deadlift', 'spinal-erectors', 'secondary'::public.muscle_role),
    ('barbell-preacher-biceps-curl', 'biceps-brachii', 'primary'::public.muscle_role),
    ('barbell-preacher-biceps-curl', 'forearms', 'secondary'::public.muscle_role),
    ('barbell-plate-ab-twist', 'core', 'primary'::public.muscle_role),
    ('barbell-plate-ab-twist', 'obliques', 'secondary'::public.muscle_role),
    ('barbell-jump-squat', 'quadriceps', 'primary'::public.muscle_role),
    ('barbell-jump-squat', 'gluteus-maximus', 'secondary'::public.muscle_role),
    ('barbell-jump-squat', 'hamstrings', 'secondary'::public.muscle_role),
    ('cable-flat-bench-triceps-extension', 'triceps-brachii', 'primary'::public.muscle_role),
    ('cable-flat-bench-triceps-extension', 'pectoralis-major', 'secondary'::public.muscle_role),
    ('cable-flat-bench-triceps-extension', 'shoulders', 'secondary'::public.muscle_role),
    ('dumbbell-preacher-biceps-curl', 'biceps-brachii', 'primary'::public.muscle_role),
    ('dumbbell-preacher-biceps-curl', 'forearms', 'secondary'::public.muscle_role),
    ('barbell-reverse-grip-bent-over-row', 'back', 'primary'::public.muscle_role),
    ('barbell-incline-bench-triceps-extension', 'triceps-brachii', 'primary'::public.muscle_role),
    ('barbell-incline-bench-triceps-extension', 'pectoralis-major', 'secondary'::public.muscle_role),
    ('barbell-incline-bench-triceps-extension', 'shoulders', 'secondary'::public.muscle_role),
    ('weighted-hanging-leg-raise', 'core', 'primary'::public.muscle_role),
    ('dumbbell-reverse-grip-bent-over-row', 'back', 'primary'::public.muscle_role),
    ('dumbbell-incline-bench-triceps-extension', 'triceps-brachii', 'primary'::public.muscle_role),
    ('dumbbell-incline-bench-triceps-extension', 'pectoralis-major', 'secondary'::public.muscle_role),
    ('dumbbell-incline-bench-triceps-extension', 'shoulders', 'secondary'::public.muscle_role),
    ('cable-incline-bench-biceps-curl', 'biceps-brachii', 'primary'::public.muscle_role),
    ('cable-incline-bench-biceps-curl', 'forearms', 'secondary'::public.muscle_role),
    ('barbell-bulgarian-split-squat', 'quadriceps', 'primary'::public.muscle_role),
    ('barbell-bulgarian-split-squat', 'gluteus-maximus', 'secondary'::public.muscle_role),
    ('barbell-bulgarian-split-squat', 'hamstrings', 'secondary'::public.muscle_role),
    ('dumbbell-stiff-legged-deadlift', 'hamstrings', 'primary'::public.muscle_role),
    ('dumbbell-stiff-legged-deadlift', 'gluteus-maximus', 'secondary'::public.muscle_role),
    ('dumbbell-stiff-legged-deadlift', 'spinal-erectors', 'secondary'::public.muscle_role),
    ('cable-incline-bench-triceps-extension', 'triceps-brachii', 'primary'::public.muscle_role),
    ('cable-incline-bench-triceps-extension', 'pectoralis-major', 'secondary'::public.muscle_role),
    ('cable-incline-bench-triceps-extension', 'shoulders', 'secondary'::public.muscle_role),
    ('weighted-plank', 'core', 'primary'::public.muscle_role),
    ('machine-decline-chest-press', 'pectoralis-major', 'primary'::public.muscle_role),
    ('machine-decline-chest-press', 'shoulders', 'secondary'::public.muscle_role),
    ('machine-decline-chest-press', 'triceps-brachii', 'secondary'::public.muscle_role),
    ('barbell-decline-bench-triceps-extension', 'triceps-brachii', 'primary'::public.muscle_role),
    ('barbell-decline-bench-triceps-extension', 'pectoralis-major', 'secondary'::public.muscle_role),
    ('barbell-decline-bench-triceps-extension', 'shoulders', 'secondary'::public.muscle_role),
    ('dumbbell-reverse-grip-biceps-curl', 'biceps-brachii', 'primary'::public.muscle_role),
    ('dumbbell-reverse-grip-biceps-curl', 'forearms', 'secondary'::public.muscle_role),
    ('bodyweight-bulgarian-split-squat', 'quadriceps', 'primary'::public.muscle_role),
    ('bodyweight-bulgarian-split-squat', 'gluteus-maximus', 'secondary'::public.muscle_role),
    ('bodyweight-bulgarian-split-squat', 'hamstrings', 'secondary'::public.muscle_role),
    ('dumbbell-hip-thrust', 'gluteus-maximus', 'primary'::public.muscle_role),
    ('barbell-one-arm-row', 'back', 'primary'::public.muscle_role),
    ('barbell-one-arm-row', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('barbell-one-arm-row', 'posterior-deltoid', 'secondary'::public.muscle_role),
    ('dumbbell-decline-bench-triceps-extension', 'triceps-brachii', 'primary'::public.muscle_role),
    ('dumbbell-decline-bench-triceps-extension', 'pectoralis-major', 'secondary'::public.muscle_role),
    ('dumbbell-decline-bench-triceps-extension', 'shoulders', 'secondary'::public.muscle_role),
    ('smith-machine-bent-over-row', 'back', 'primary'::public.muscle_role),
    ('smith-machine-bent-over-row', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('smith-machine-bent-over-row', 'posterior-deltoid', 'secondary'::public.muscle_role),
    ('cable-standing-shoulder-press', 'shoulders', 'primary'::public.muscle_role),
    ('cable-standing-shoulder-press', 'triceps-brachii', 'secondary'::public.muscle_role),
    ('cable-decline-bench-triceps-extension', 'triceps-brachii', 'primary'::public.muscle_role),
    ('cable-decline-bench-triceps-extension', 'pectoralis-major', 'secondary'::public.muscle_role),
    ('cable-decline-bench-triceps-extension', 'shoulders', 'secondary'::public.muscle_role),
    ('barbell-concentration-biceps-curl', 'biceps-brachii', 'primary'::public.muscle_role),
    ('barbell-concentration-biceps-curl', 'forearms', 'secondary'::public.muscle_role),
    ('dumbbell-glute-bridge', 'gluteus-maximus', 'primary'::public.muscle_role),
    ('smith-machine-decline-chest-press', 'pectoralis-major', 'primary'::public.muscle_role),
    ('smith-machine-decline-chest-press', 'shoulders', 'secondary'::public.muscle_role),
    ('smith-machine-decline-chest-press', 'triceps-brachii', 'secondary'::public.muscle_role),
    ('barbell-chest-supported-t-bar-row', 'back', 'primary'::public.muscle_role),
    ('barbell-chest-supported-t-bar-row', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('barbell-chest-supported-t-bar-row', 'posterior-deltoid', 'secondary'::public.muscle_role),
    ('seated-cable-shoulder-press', 'shoulders', 'primary'::public.muscle_role),
    ('seated-cable-shoulder-press', 'triceps-brachii', 'secondary'::public.muscle_role),
    ('barbell-overhead-triceps-extension', 'triceps-brachii', 'primary'::public.muscle_role),
    ('bodyweight-walking-lunge', 'quadriceps', 'primary'::public.muscle_role),
    ('bodyweight-walking-lunge', 'gluteus-maximus', 'secondary'::public.muscle_role),
    ('bodyweight-walking-lunge', 'hamstrings', 'secondary'::public.muscle_role),
    ('zercher-carries', 'core', 'primary'::public.muscle_role),
    ('zercher-carries', 'forearms', 'secondary'::public.muscle_role),
    ('zercher-carries', 'upper-back', 'secondary'::public.muscle_role),
    ('barbell-standing-lunge', 'quadriceps', 'primary'::public.muscle_role),
    ('barbell-standing-lunge', 'gluteus-maximus', 'secondary'::public.muscle_role),
    ('barbell-standing-lunge', 'hamstrings', 'secondary'::public.muscle_role),
    ('cable-incline-bench-press', 'pectoralis-major', 'primary'::public.muscle_role),
    ('cable-incline-bench-press', 'shoulders', 'secondary'::public.muscle_role),
    ('cable-incline-bench-press', 'triceps-brachii', 'secondary'::public.muscle_role),
    ('barbell-front-raise', 'anterior-deltoid', 'primary'::public.muscle_role),
    ('cable-one-arm-overhead-triceps-extension', 'triceps-brachii', 'primary'::public.muscle_role),
    ('machine-biceps-curl', 'biceps-brachii', 'primary'::public.muscle_role),
    ('machine-biceps-curl', 'forearms', 'secondary'::public.muscle_role),
    ('barbell-step-up', 'quadriceps', 'primary'::public.muscle_role),
    ('barbell-step-up', 'gluteus-maximus', 'secondary'::public.muscle_role),
    ('barbell-step-up', 'hamstrings', 'secondary'::public.muscle_role),
    ('weighted-push-up', 'pectoralis-major', 'primary'::public.muscle_role),
    ('weighted-push-up', 'shoulders', 'secondary'::public.muscle_role),
    ('weighted-push-up', 'triceps-brachii', 'secondary'::public.muscle_role),
    ('machine-iso-row', 'back', 'primary'::public.muscle_role),
    ('machine-iso-row', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('machine-iso-row', 'posterior-deltoid', 'secondary'::public.muscle_role),
    ('cable-overhead-curl', 'biceps-brachii', 'primary'::public.muscle_role),
    ('cable-overhead-curl', 'forearms', 'secondary'::public.muscle_role),
    ('bodyweight-glute-ham-raise', 'hamstrings', 'primary'::public.muscle_role),
    ('bodyweight-glute-ham-raise', 'gluteus-maximus', 'secondary'::public.muscle_role),
    ('bodyweight-glute-ham-raise', 'spinal-erectors', 'secondary'::public.muscle_role),
    ('weighted-pull-up', 'back', 'primary'::public.muscle_role),
    ('weighted-pull-up', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('weighted-pull-up', 'posterior-deltoid', 'secondary'::public.muscle_role),
    ('dumbbell-one-arm-lateral-raise', 'lateral-deltoid', 'primary'::public.muscle_role),
    ('weighted-incline-push-up', 'pectoralis-major', 'primary'::public.muscle_role),
    ('weighted-incline-push-up', 'shoulders', 'secondary'::public.muscle_role),
    ('weighted-incline-push-up', 'triceps-brachii', 'secondary'::public.muscle_role),
    ('dumbbell-bent-over-triceps-extension', 'triceps-brachii', 'primary'::public.muscle_role),
    ('dumbbell-one-arm-biceps-curl', 'biceps-brachii', 'primary'::public.muscle_role),
    ('dumbbell-one-arm-biceps-curl', 'forearms', 'secondary'::public.muscle_role),
    ('smith-machine-close-grip-bench-press', 'triceps-brachii', 'primary'::public.muscle_role),
    ('smith-machine-close-grip-bench-press', 'pectoralis-major', 'secondary'::public.muscle_role),
    ('smith-machine-close-grip-bench-press', 'shoulders', 'secondary'::public.muscle_role),
    ('cable-one-arm-biceps-curl', 'biceps-brachii', 'primary'::public.muscle_role),
    ('cable-one-arm-biceps-curl', 'forearms', 'secondary'::public.muscle_role),
    ('machine-hip-thrust', 'gluteus-maximus', 'primary'::public.muscle_role),
    ('weighted-decline-push-up', 'pectoralis-major', 'primary'::public.muscle_role),
    ('weighted-decline-push-up', 'shoulders', 'secondary'::public.muscle_role),
    ('weighted-decline-push-up', 'triceps-brachii', 'secondary'::public.muscle_role),
    ('weighted-triceps-dip', 'triceps-brachii', 'primary'::public.muscle_role),
    ('weighted-triceps-dip', 'pectoralis-major', 'secondary'::public.muscle_role),
    ('weighted-triceps-dip', 'shoulders', 'secondary'::public.muscle_role),
    ('weighted-chin-up', 'biceps-brachii', 'primary'::public.muscle_role),
    ('weighted-chin-up', 'back', 'secondary'::public.muscle_role),
    ('cable-reverse-grip-lat-pulldown', 'back', 'primary'::public.muscle_role),
    ('cable-reverse-grip-lat-pulldown', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('cable-reverse-grip-lat-pulldown', 'posterior-deltoid', 'secondary'::public.muscle_role),
    ('machine-assisted-chin-up', 'biceps-brachii', 'primary'::public.muscle_role),
    ('machine-assisted-chin-up', 'back', 'secondary'::public.muscle_role),
    ('cable-v-bar-lat-pulldown', 'back', 'primary'::public.muscle_role),
    ('cable-v-bar-lat-pulldown', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('cable-v-bar-lat-pulldown', 'posterior-deltoid', 'secondary'::public.muscle_role),
    ('cable-one-arm-lat-pulldown', 'back', 'primary'::public.muscle_role),
    ('cable-one-arm-lat-pulldown', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('cable-one-arm-lat-pulldown', 'posterior-deltoid', 'secondary'::public.muscle_role),
    ('cable-v-bar-triceps-pushdown', 'triceps-brachii', 'primary'::public.muscle_role),
    ('dumbbell-decline-bench-fly', 'pectoralis-major', 'primary'::public.muscle_role),
    ('dumbbell-decline-bench-fly', 'shoulders', 'secondary'::public.muscle_role),
    ('dumbbell-decline-bench-fly', 'triceps-brachii', 'secondary'::public.muscle_role),
    ('machine-back-extension', 'back', 'primary'::public.muscle_role),
    ('machine-back-extension', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('machine-back-extension', 'posterior-deltoid', 'secondary'::public.muscle_role),
    ('cable-reverse-grip-triceps-pushdown', 'triceps-brachii', 'primary'::public.muscle_role),
    ('machine-upright-row', 'shoulders', 'primary'::public.muscle_role),
    ('weighted-bench-dip', 'triceps-brachii', 'primary'::public.muscle_role),
    ('weighted-bench-dip', 'pectoralis-major', 'secondary'::public.muscle_role),
    ('weighted-bench-dip', 'shoulders', 'secondary'::public.muscle_role),
    ('cable-upright-row', 'shoulders', 'primary'::public.muscle_role),
    ('machine-shrug', 'back', 'primary'::public.muscle_role),
    ('machine-shrug', 'trapezius', 'secondary'::public.muscle_role),
    ('cable-incline-bench-fly', 'pectoralis-major', 'primary'::public.muscle_role),
    ('cable-incline-bench-fly', 'shoulders', 'secondary'::public.muscle_role),
    ('cable-incline-bench-fly', 'triceps-brachii', 'secondary'::public.muscle_role),
    ('smith-machine-chest-supported-row', 'back', 'primary'::public.muscle_role),
    ('smith-machine-chest-supported-row', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('smith-machine-chest-supported-row', 'posterior-deltoid', 'secondary'::public.muscle_role),
    ('cable-flat-bench-fly', 'pectoralis-major', 'primary'::public.muscle_role),
    ('cable-flat-bench-fly', 'shoulders', 'secondary'::public.muscle_role),
    ('cable-flat-bench-fly', 'triceps-brachii', 'secondary'::public.muscle_role),
    ('machine-chest-supported-low-row', 'back', 'primary'::public.muscle_role),
    ('machine-chest-supported-low-row', 'biceps-brachii', 'secondary'::public.muscle_role),
    ('machine-chest-supported-low-row', 'posterior-deltoid', 'secondary'::public.muscle_role)
)
insert into public.exercise_muscles (exercise_id, muscle_id, role)
select e.id, m.id, sem.role
from seed_exercise_muscles sem
join public.exercises e on e.slug = sem.exercise_slug and e.is_builtin = true
join public.muscles m on m.slug = sem.muscle_slug
on conflict (exercise_id, muscle_id, role) do nothing;
