-- Adds common missing exercises from common public exercise directories and gym programming patterns.
-- Keeps the existing exercises and exercise_muscles format. Bodyweight remains equipment, not load.

insert into public.muscles (name, slug, muscle_group, body_region)
values
  ('Cardio', 'cardio', 'full_body', 'full'),
  ('Full Body', 'full-body', 'full_body', 'full')
on conflict (slug) do update
set
  name = excluded.name,
  muscle_group = excluded.muscle_group,
  body_region = excluded.body_region;

with seed_exercises (name, slug, category, equipment, movement_pattern, difficulty, instructions, notes) as (
  values
    ('Decline Barbell Bench Press', 'decline-barbell-bench-press', 'chest', array['barbell', 'bench'], 'decline horizontal push', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Decline Dumbbell Bench Press', 'decline-dumbbell-bench-press', 'chest', array['dumbbell', 'bench'], 'decline horizontal push', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Smith Machine Bench Press', 'smith-machine-bench-press', 'chest', array['smith machine', 'bench'], 'horizontal push', 'beginner', null, 'Added from common exercise gap audit'),
    ('Smith Machine Incline Bench Press', 'smith-machine-incline-bench-press', 'chest', array['smith machine', 'bench'], 'incline horizontal push', 'beginner', null, 'Added from common exercise gap audit'),
    ('Machine Incline Chest Press', 'machine-incline-chest-press', 'chest', array['machine'], 'incline horizontal push', 'beginner', null, 'Added from common exercise gap audit'),
    ('Machine Fly', 'machine-fly', 'chest', array['machine'], 'fly', 'beginner', null, 'Added from common exercise gap audit'),
    ('Dumbbell Fly', 'dumbbell-fly', 'chest', array['dumbbell', 'bench'], 'fly', 'beginner', null, 'Added from common exercise gap audit'),
    ('Incline Dumbbell Fly', 'incline-dumbbell-fly', 'chest', array['dumbbell', 'bench'], 'incline fly', 'beginner', null, 'Added from common exercise gap audit'),
    ('Low-to-High Cable Fly', 'low-to-high-cable-fly', 'chest', array['cable'], 'incline fly', 'intermediate', null, 'Added from common exercise gap audit'),
    ('High-to-Low Cable Fly', 'high-to-low-cable-fly', 'chest', array['cable'], 'decline fly', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Knee Push-Up', 'knee-push-up', 'chest', array['bodyweight'], 'horizontal push', 'beginner', null, 'Added from common exercise gap audit'),
    ('Close-Grip Push-Up', 'close-grip-push-up', 'triceps', array['bodyweight'], 'horizontal push', 'beginner', null, 'Added from common exercise gap audit'),
    ('Ring Push-Up', 'ring-push-up', 'chest', array['rings', 'bodyweight'], 'horizontal push', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Dumbbell Pullover', 'dumbbell-pullover', 'back', array['dumbbell', 'bench'], 'pullover', 'beginner', null, 'Added from common exercise gap audit'),
    ('T-Bar Row', 't-bar-row', 'back', array['barbell', 'landmine'], 'horizontal pull', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Landmine Row', 'landmine-row', 'back', array['barbell', 'landmine'], 'horizontal pull', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Pendlay Row', 'pendlay-row', 'back', array['barbell'], 'horizontal pull', 'advanced', null, 'Added from common exercise gap audit'),
    ('Meadows Row', 'meadows-row', 'back', array['barbell', 'landmine'], 'horizontal pull', 'advanced', null, 'Added from common exercise gap audit'),
    ('Single-Arm Cable Row', 'single-arm-cable-row', 'back', array['cable'], 'horizontal pull', 'beginner', null, 'Added from common exercise gap audit'),
    ('Wide-Grip Lat Pulldown', 'wide-grip-lat-pulldown', 'back', array['cable'], 'vertical pull', 'beginner', null, 'Added from common exercise gap audit'),
    ('Neutral-Grip Lat Pulldown', 'neutral-grip-lat-pulldown', 'back', array['cable'], 'vertical pull', 'beginner', null, 'Added from common exercise gap audit'),
    ('Close-Grip Lat Pulldown', 'close-grip-lat-pulldown', 'back', array['cable'], 'vertical pull', 'beginner', null, 'Added from common exercise gap audit'),
    ('Inverted Row', 'inverted-row', 'back', array['bodyweight', 'bar'], 'horizontal pull', 'beginner', null, 'Added from common exercise gap audit'),
    ('Machine Row', 'machine-row', 'back', array['machine'], 'horizontal pull', 'beginner', null, 'Added from common exercise gap audit'),
    ('Hammer Strength Row', 'hammer-strength-row', 'back', array['machine'], 'horizontal pull', 'beginner', null, 'Added from common exercise gap audit'),
    ('Assisted Pull-Up', 'assisted-pull-up', 'back', array['machine', 'pull-up bar'], 'vertical pull', 'beginner', null, 'Added from common exercise gap audit'),
    ('Rack Pull', 'rack-pull', 'back', array['barbell', 'rack'], 'hip hinge', 'advanced', null, 'Added from common exercise gap audit'),
    ('Chest-Supported Dumbbell Row', 'chest-supported-dumbbell-row', 'back', array['dumbbell', 'bench'], 'horizontal pull', 'beginner', null, 'Added from common exercise gap audit'),
    ('Chest-Supported Machine Row', 'chest-supported-machine-row', 'back', array['machine'], 'horizontal pull', 'beginner', null, 'Added from common exercise gap audit'),
    ('Straight-Arm Pulldown', 'straight-arm-pulldown', 'back', array['cable'], 'pullover', 'beginner', null, 'Added from common exercise gap audit'),
    ('Arnold Press', 'arnold-press', 'shoulders', array['dumbbell'], 'vertical push', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Seated Dumbbell Shoulder Press', 'seated-dumbbell-shoulder-press', 'shoulders', array['dumbbell', 'bench'], 'vertical push', 'beginner', null, 'Added from common exercise gap audit'),
    ('Seated Barbell Shoulder Press', 'seated-barbell-shoulder-press', 'shoulders', array['barbell', 'bench'], 'vertical push', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Smith Machine Shoulder Press', 'smith-machine-shoulder-press', 'shoulders', array['smith machine', 'bench'], 'vertical push', 'beginner', null, 'Added from common exercise gap audit'),
    ('Cable Front Raise', 'cable-front-raise', 'shoulders', array['cable'], 'shoulder flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Plate Front Raise', 'plate-front-raise', 'shoulders', array['weight plate'], 'shoulder flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Reverse Pec Deck', 'reverse-pec-deck', 'shoulders', array['machine'], 'reverse fly', 'beginner', null, 'Added from common exercise gap audit'),
    ('Machine Lateral Raise', 'machine-lateral-raise', 'shoulders', array['machine'], 'shoulder abduction', 'beginner', null, 'Added from common exercise gap audit'),
    ('Leaning Cable Lateral Raise', 'leaning-cable-lateral-raise', 'shoulders', array['cable'], 'shoulder abduction', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Dumbbell Shrug', 'dumbbell-shrug', 'back', array['dumbbell'], 'shrug', 'beginner', null, 'Added from common exercise gap audit'),
    ('Face Pull with External Rotation', 'face-pull-with-external-rotation', 'shoulders', array['cable'], 'horizontal pull', 'intermediate', null, 'Added from common exercise gap audit'),
    ('EZ-Bar Curl', 'ez-bar-curl', 'biceps', array['ez bar'], 'elbow flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Incline Dumbbell Curl', 'incline-dumbbell-curl', 'biceps', array['dumbbell', 'bench'], 'elbow flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Dumbbell Concentration Curl', 'dumbbell-concentration-curl', 'biceps', array['dumbbell'], 'elbow flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Spider Curl', 'spider-curl', 'biceps', array['dumbbell', 'bench'], 'elbow flexion', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Bayesian Cable Curl', 'bayesian-cable-curl', 'biceps', array['cable'], 'elbow flexion', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Rope Cable Curl', 'rope-cable-curl', 'biceps', array['cable'], 'elbow flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Cable Hammer Curl', 'cable-hammer-curl', 'biceps', array['cable'], 'elbow flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Zottman Curl', 'zottman-curl', 'biceps', array['dumbbell'], 'elbow flexion', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Machine Preacher Curl', 'machine-preacher-curl', 'biceps', array['machine'], 'elbow flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Barbell Close-Grip Bench Press', 'barbell-close-grip-bench-press', 'triceps', array['barbell', 'bench'], 'horizontal push', 'intermediate', null, 'Added from common exercise gap audit'),
    ('JM Press', 'jm-press', 'triceps', array['barbell', 'bench'], 'elbow extension', 'advanced', null, 'Added from common exercise gap audit'),
    ('Bench Dip', 'bench-dip', 'triceps', array['bodyweight', 'bench'], 'elbow extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Diamond Push-Up', 'diamond-push-up', 'triceps', array['bodyweight'], 'horizontal push', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Cable Overhead Triceps Extension', 'cable-overhead-triceps-extension', 'triceps', array['cable'], 'elbow extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Rope Overhead Triceps Extension', 'rope-overhead-triceps-extension', 'triceps', array['cable'], 'elbow extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Lying Triceps Extension', 'lying-triceps-extension', 'triceps', array['ez bar', 'bench'], 'elbow extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Dumbbell Skull Crusher', 'dumbbell-skull-crusher', 'triceps', array['dumbbell', 'bench'], 'elbow extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Cable Triceps Kickback', 'cable-triceps-kickback', 'triceps', array['cable'], 'elbow extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Machine Triceps Extension', 'machine-triceps-extension', 'triceps', array['machine'], 'elbow extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Reverse Wrist Curl', 'reverse-wrist-curl', 'forearms', array['dumbbell'], 'wrist extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Plate Pinch', 'plate-pinch', 'forearms', array['weight plate'], 'grip', 'beginner', null, 'Added from common exercise gap audit'),
    ('Dead Hang', 'dead-hang', 'forearms', array['pull-up bar', 'bodyweight'], 'grip', 'beginner', null, 'Added from common exercise gap audit'),
    ('Wrist Roller', 'wrist-roller', 'forearms', array['wrist roller'], 'grip', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Dumbbell Wrist Curl', 'dumbbell-wrist-curl', 'forearms', array['dumbbell'], 'wrist flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Dumbbell Reverse Wrist Curl', 'dumbbell-reverse-wrist-curl', 'forearms', array['dumbbell'], 'wrist extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Goblet Squat', 'goblet-squat', 'quads', array['dumbbell', 'kettlebell'], 'squat', 'beginner', null, 'Added from common exercise gap audit'),
    ('Smith Machine Squat', 'smith-machine-squat', 'quads', array['smith machine'], 'squat', 'beginner', null, 'Added from common exercise gap audit'),
    ('Sissy Squat', 'sissy-squat', 'quads', array['bodyweight'], 'knee extension', 'advanced', null, 'Added from common exercise gap audit'),
    ('Belt Squat', 'belt-squat', 'quads', array['machine'], 'squat', 'beginner', null, 'Added from common exercise gap audit'),
    ('Pistol Squat', 'pistol-squat', 'quads', array['bodyweight'], 'squat', 'advanced', null, 'Added from common exercise gap audit'),
    ('Step-Up', 'step-up', 'quads', array['bodyweight', 'box'], 'lunge', 'beginner', null, 'Added from common exercise gap audit'),
    ('Reverse Lunge', 'reverse-lunge', 'quads', array['dumbbell'], 'lunge', 'beginner', null, 'Added from common exercise gap audit'),
    ('Forward Lunge', 'forward-lunge', 'quads', array['dumbbell'], 'lunge', 'beginner', null, 'Added from common exercise gap audit'),
    ('Split Squat', 'split-squat', 'quads', array['dumbbell'], 'lunge', 'beginner', null, 'Added from common exercise gap audit'),
    ('Smith Machine Bulgarian Split Squat', 'smith-machine-bulgarian-split-squat', 'quads', array['smith machine'], 'lunge', 'beginner', null, 'Added from common exercise gap audit'),
    ('Walking Dumbbell Lunge', 'walking-dumbbell-lunge', 'quads', array['dumbbell'], 'lunge', 'beginner', null, 'Added from common exercise gap audit'),
    ('Box Step-Up', 'box-step-up', 'quads', array['box', 'bodyweight'], 'lunge', 'beginner', null, 'Added from common exercise gap audit'),
    ('Wall Sit', 'wall-sit', 'quads', array['bodyweight', 'wall'], 'isometric squat', 'beginner', null, 'Added from common exercise gap audit'),
    ('Nordic Hamstring Curl', 'nordic-hamstring-curl', 'hamstrings', array['bodyweight'], 'knee flexion', 'advanced', null, 'Added from common exercise gap audit'),
    ('Lying Leg Curl', 'lying-leg-curl', 'hamstrings', array['machine'], 'knee flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Good Morning', 'good-morning', 'hamstrings', array['barbell'], 'hip hinge', 'advanced', null, 'Added from common exercise gap audit'),
    ('Single-Leg Romanian Deadlift', 'single-leg-romanian-deadlift', 'hamstrings', array['dumbbell'], 'hip hinge', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Cable Pull-Through', 'cable-pull-through', 'glutes', array['cable'], 'hip hinge', 'beginner', null, 'Added from common exercise gap audit'),
    ('Glute-Ham Raise', 'glute-ham-raise', 'hamstrings', array['bodyweight', 'glute ham developer'], 'knee flexion', 'advanced', null, 'Added from common exercise gap audit'),
    ('45-Degree Back Extension', '45-degree-back-extension', 'back', array['back extension bench'], 'spinal extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Reverse Hyperextension', 'reverse-hyperextension', 'glutes', array['machine'], 'hip extension', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Dumbbell Romanian Deadlift', 'dumbbell-romanian-deadlift', 'hamstrings', array['dumbbell'], 'hip hinge', 'beginner', null, 'Added from common exercise gap audit'),
    ('Smith Machine Romanian Deadlift', 'smith-machine-romanian-deadlift', 'hamstrings', array['smith machine'], 'hip hinge', 'beginner', null, 'Added from common exercise gap audit'),
    ('Barbell Glute Bridge', 'barbell-glute-bridge', 'glutes', array['barbell', 'bench'], 'hip thrust', 'beginner', null, 'Added from common exercise gap audit'),
    ('Hip Abduction Machine', 'hip-abduction-machine', 'glutes', array['machine'], 'hip abduction', 'beginner', null, 'Added from common exercise gap audit'),
    ('Cable Hip Abduction', 'cable-hip-abduction', 'glutes', array['cable'], 'hip abduction', 'beginner', null, 'Added from common exercise gap audit'),
    ('Machine Glute Kickback', 'machine-glute-kickback', 'glutes', array['machine'], 'hip extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Frog Pump', 'frog-pump', 'glutes', array['bodyweight'], 'hip thrust', 'beginner', null, 'Added from common exercise gap audit'),
    ('Banded Lateral Walk', 'banded-lateral-walk', 'glutes', array['resistance band'], 'hip abduction', 'beginner', null, 'Added from common exercise gap audit'),
    ('Clamshell', 'clamshell', 'glutes', array['bodyweight', 'resistance band'], 'hip abduction', 'beginner', null, 'Added from common exercise gap audit'),
    ('Single-Leg Hip Thrust', 'single-leg-hip-thrust', 'glutes', array['bodyweight', 'bench'], 'hip thrust', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Donkey Calf Raise', 'donkey-calf-raise', 'calves', array['machine'], 'calf raise', 'beginner', null, 'Added from common exercise gap audit'),
    ('Leg Press Calf Raise', 'leg-press-calf-raise', 'calves', array['leg press'], 'calf raise', 'beginner', null, 'Added from common exercise gap audit'),
    ('Single-Leg Calf Raise', 'single-leg-calf-raise', 'calves', array['bodyweight'], 'calf raise', 'beginner', null, 'Added from common exercise gap audit'),
    ('Smith Machine Calf Raise', 'smith-machine-calf-raise', 'calves', array['smith machine'], 'calf raise', 'beginner', null, 'Added from common exercise gap audit'),
    ('Dumbbell Calf Raise', 'dumbbell-calf-raise', 'calves', array['dumbbell'], 'calf raise', 'beginner', null, 'Added from common exercise gap audit'),
    ('Ab Wheel Rollout', 'ab-wheel-rollout', 'core', array['ab wheel'], 'anti-extension', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Crunch', 'crunch', 'core', array['bodyweight'], 'trunk flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Reverse Crunch', 'reverse-crunch', 'core', array['bodyweight'], 'trunk flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Bicycle Crunch', 'bicycle-crunch', 'core', array['bodyweight'], 'trunk rotation', 'beginner', null, 'Added from common exercise gap audit'),
    ('Sit-Up', 'sit-up', 'core', array['bodyweight'], 'trunk flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('V-Up', 'v-up', 'core', array['bodyweight'], 'trunk flexion', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Flutter Kick', 'flutter-kick', 'core', array['bodyweight'], 'hip flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Mountain Climber', 'mountain-climber', 'core', array['bodyweight'], 'conditioning', 'beginner', null, 'Added from common exercise gap audit'),
    ('Hanging Leg Raise', 'hanging-leg-raise', 'core', array['pull-up bar', 'bodyweight'], 'hip flexion', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Captain Chair Leg Raise', 'captain-chair-leg-raise', 'core', array['captain chair'], 'hip flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Cable Wood Chop', 'cable-wood-chop', 'core', array['cable'], 'trunk rotation', 'beginner', null, 'Added from common exercise gap audit'),
    ('Medicine Ball Russian Twist', 'medicine-ball-russian-twist', 'core', array['medicine ball'], 'trunk rotation', 'beginner', null, 'Added from common exercise gap audit'),
    ('Toe Touch Crunch', 'toe-touch-crunch', 'core', array['bodyweight'], 'trunk flexion', 'beginner', null, 'Added from common exercise gap audit'),
    ('Hollow Body Hold', 'hollow-body-hold', 'core', array['bodyweight'], 'anti-extension', 'beginner', null, 'Added from common exercise gap audit'),
    ('Burpee', 'burpee', 'full_body', array['bodyweight'], 'conditioning', 'beginner', null, 'Added from common exercise gap audit'),
    ('Box Jump', 'box-jump', 'quads', array['box'], 'plyometric', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Jump Rope', 'jump-rope', 'cardio', array['jump rope'], 'conditioning', 'beginner', null, 'Added from common exercise gap audit'),
    ('Battle Ropes', 'battle-ropes', 'cardio', array['battle ropes'], 'conditioning', 'beginner', null, 'Added from common exercise gap audit'),
    ('Elliptical', 'elliptical', 'cardio', array['elliptical'], 'conditioning', 'beginner', null, 'Added from common exercise gap audit'),
    ('Assault Bike', 'assault-bike', 'cardio', array['bike'], 'conditioning', 'beginner', null, 'Added from common exercise gap audit'),
    ('SkiErg', 'skierg', 'cardio', array['skierg'], 'conditioning', 'beginner', null, 'Added from common exercise gap audit'),
    ('Sled Pull', 'sled-pull', 'quads', array['sled'], 'loaded carry', 'beginner', null, 'Added from common exercise gap audit'),
    ('Wall Ball', 'wall-ball', 'quads', array['medicine ball'], 'conditioning', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Thruster', 'thruster', 'full_body', array['barbell'], 'squat to press', 'intermediate', null, 'Added from common exercise gap audit'),
    ('Medicine Ball Slam', 'medicine-ball-slam', 'full_body', array['medicine ball'], 'conditioning', 'beginner', null, 'Added from common exercise gap audit'),
    ('Turkish Get-Up', 'turkish-get-up', 'full_body', array['kettlebell'], 'floor to stand', 'advanced', null, 'Added from common exercise gap audit'),
    ('Kettlebell Turkish Get-Up', 'kettlebell-turkish-get-up', 'full_body', array['kettlebell'], 'floor to stand', 'advanced', null, 'Added from common exercise gap audit'),
    ('Bear Crawl', 'bear-crawl', 'full_body', array['bodyweight'], 'crawl', 'beginner', null, 'Added from common exercise gap audit'),
    ('Clean and Jerk', 'clean-and-jerk', 'full_body', array['barbell'], 'olympic lift', 'advanced', null, 'Added from common exercise gap audit'),
    ('Snatch', 'snatch', 'full_body', array['barbell'], 'olympic lift', 'advanced', null, 'Added from common exercise gap audit'),
    ('Power Clean', 'power-clean', 'full_body', array['barbell'], 'olympic lift', 'advanced', null, 'Added from common exercise gap audit'),
    ('Hang Clean', 'hang-clean', 'full_body', array['barbell'], 'olympic lift', 'advanced', null, 'Added from common exercise gap audit')
)
insert into public.exercises (name, slug, category, equipment, movement_pattern, difficulty, instructions, notes, is_builtin)
select se.name, se.slug, se.category::public.exercise_category, se.equipment, se.movement_pattern, se.difficulty::public.difficulty_level, se.instructions, se.notes, true
from seed_exercises se
where not exists (
  select 1 from public.exercises e where e.slug = se.slug and e.is_builtin = true
);

with seed_primary_muscles (exercise_slug, muscle_slug) as (
  values
    ('decline-barbell-bench-press', 'pectoralis-major'),
    ('decline-dumbbell-bench-press', 'pectoralis-major'),
    ('smith-machine-bench-press', 'pectoralis-major'),
    ('smith-machine-incline-bench-press', 'pectoralis-major'),
    ('machine-incline-chest-press', 'pectoralis-major'),
    ('machine-fly', 'pectoralis-major'),
    ('dumbbell-fly', 'pectoralis-major'),
    ('incline-dumbbell-fly', 'pectoralis-major'),
    ('low-to-high-cable-fly', 'pectoralis-major'),
    ('high-to-low-cable-fly', 'pectoralis-major'),
    ('knee-push-up', 'pectoralis-major'),
    ('close-grip-push-up', 'triceps-brachii'),
    ('ring-push-up', 'pectoralis-major'),
    ('dumbbell-pullover', 'back'),
    ('t-bar-row', 'back'),
    ('landmine-row', 'back'),
    ('pendlay-row', 'back'),
    ('meadows-row', 'back'),
    ('single-arm-cable-row', 'back'),
    ('wide-grip-lat-pulldown', 'back'),
    ('neutral-grip-lat-pulldown', 'back'),
    ('close-grip-lat-pulldown', 'back'),
    ('inverted-row', 'back'),
    ('machine-row', 'back'),
    ('hammer-strength-row', 'back'),
    ('assisted-pull-up', 'back'),
    ('rack-pull', 'back'),
    ('chest-supported-dumbbell-row', 'back'),
    ('chest-supported-machine-row', 'back'),
    ('straight-arm-pulldown', 'back'),
    ('arnold-press', 'shoulders'),
    ('seated-dumbbell-shoulder-press', 'shoulders'),
    ('seated-barbell-shoulder-press', 'shoulders'),
    ('smith-machine-shoulder-press', 'shoulders'),
    ('cable-front-raise', 'shoulders'),
    ('plate-front-raise', 'shoulders'),
    ('reverse-pec-deck', 'shoulders'),
    ('machine-lateral-raise', 'shoulders'),
    ('leaning-cable-lateral-raise', 'shoulders'),
    ('dumbbell-shrug', 'back'),
    ('face-pull-with-external-rotation', 'shoulders'),
    ('ez-bar-curl', 'biceps-brachii'),
    ('incline-dumbbell-curl', 'biceps-brachii'),
    ('dumbbell-concentration-curl', 'biceps-brachii'),
    ('spider-curl', 'biceps-brachii'),
    ('bayesian-cable-curl', 'biceps-brachii'),
    ('rope-cable-curl', 'biceps-brachii'),
    ('cable-hammer-curl', 'biceps-brachii'),
    ('zottman-curl', 'biceps-brachii'),
    ('machine-preacher-curl', 'biceps-brachii'),
    ('barbell-close-grip-bench-press', 'triceps-brachii'),
    ('jm-press', 'triceps-brachii'),
    ('bench-dip', 'triceps-brachii'),
    ('diamond-push-up', 'triceps-brachii'),
    ('cable-overhead-triceps-extension', 'triceps-brachii'),
    ('rope-overhead-triceps-extension', 'triceps-brachii'),
    ('lying-triceps-extension', 'triceps-brachii'),
    ('dumbbell-skull-crusher', 'triceps-brachii'),
    ('cable-triceps-kickback', 'triceps-brachii'),
    ('machine-triceps-extension', 'triceps-brachii'),
    ('reverse-wrist-curl', 'forearms'),
    ('plate-pinch', 'forearms'),
    ('dead-hang', 'forearms'),
    ('wrist-roller', 'forearms'),
    ('dumbbell-wrist-curl', 'forearms'),
    ('dumbbell-reverse-wrist-curl', 'forearms'),
    ('goblet-squat', 'quadriceps'),
    ('smith-machine-squat', 'quadriceps'),
    ('sissy-squat', 'quadriceps'),
    ('belt-squat', 'quadriceps'),
    ('pistol-squat', 'quadriceps'),
    ('step-up', 'quadriceps'),
    ('reverse-lunge', 'quadriceps'),
    ('forward-lunge', 'quadriceps'),
    ('split-squat', 'quadriceps'),
    ('smith-machine-bulgarian-split-squat', 'quadriceps'),
    ('walking-dumbbell-lunge', 'quadriceps'),
    ('box-step-up', 'quadriceps'),
    ('wall-sit', 'quadriceps'),
    ('nordic-hamstring-curl', 'hamstrings'),
    ('lying-leg-curl', 'hamstrings'),
    ('good-morning', 'hamstrings'),
    ('single-leg-romanian-deadlift', 'hamstrings'),
    ('cable-pull-through', 'gluteus-maximus'),
    ('glute-ham-raise', 'hamstrings'),
    ('45-degree-back-extension', 'back'),
    ('reverse-hyperextension', 'gluteus-maximus'),
    ('dumbbell-romanian-deadlift', 'hamstrings'),
    ('smith-machine-romanian-deadlift', 'hamstrings'),
    ('barbell-glute-bridge', 'gluteus-maximus'),
    ('hip-abduction-machine', 'gluteus-maximus'),
    ('cable-hip-abduction', 'gluteus-maximus'),
    ('machine-glute-kickback', 'gluteus-maximus'),
    ('frog-pump', 'gluteus-maximus'),
    ('banded-lateral-walk', 'gluteus-maximus'),
    ('clamshell', 'gluteus-maximus'),
    ('single-leg-hip-thrust', 'gluteus-maximus'),
    ('donkey-calf-raise', 'calves'),
    ('leg-press-calf-raise', 'calves'),
    ('single-leg-calf-raise', 'calves'),
    ('smith-machine-calf-raise', 'calves'),
    ('dumbbell-calf-raise', 'calves'),
    ('ab-wheel-rollout', 'core'),
    ('crunch', 'core'),
    ('reverse-crunch', 'core'),
    ('bicycle-crunch', 'core'),
    ('sit-up', 'core'),
    ('v-up', 'core'),
    ('flutter-kick', 'core'),
    ('mountain-climber', 'core'),
    ('hanging-leg-raise', 'core'),
    ('captain-chair-leg-raise', 'core'),
    ('cable-wood-chop', 'core'),
    ('medicine-ball-russian-twist', 'core'),
    ('toe-touch-crunch', 'core'),
    ('hollow-body-hold', 'core'),
    ('burpee', 'full-body'),
    ('box-jump', 'quadriceps'),
    ('jump-rope', 'cardio'),
    ('battle-ropes', 'cardio'),
    ('elliptical', 'cardio'),
    ('assault-bike', 'cardio'),
    ('skierg', 'cardio'),
    ('sled-pull', 'quadriceps'),
    ('wall-ball', 'quadriceps'),
    ('thruster', 'full-body'),
    ('medicine-ball-slam', 'full-body'),
    ('turkish-get-up', 'full-body'),
    ('kettlebell-turkish-get-up', 'full-body'),
    ('bear-crawl', 'full-body'),
    ('clean-and-jerk', 'full-body'),
    ('snatch', 'full-body'),
    ('power-clean', 'full-body'),
    ('hang-clean', 'full-body')
)
insert into public.exercise_muscles (exercise_id, muscle_id, role)
select e.id, m.id, 'primary'::public.muscle_role
from seed_primary_muscles spm
join public.exercises e on e.slug = spm.exercise_slug and e.is_builtin = true
join public.muscles m on m.slug = spm.muscle_slug
on conflict (exercise_id, muscle_id, role) do nothing;
